[package]
name = "kvs"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
failure = "0.1.8"
serde = { "version" = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"

[dev-dependencies]
assert_cmd = "2.0.2"
predicates = "2.0.3"
tempfile = "3.2.0"
walkdir = "2.3.2"